name: osaa-mvp

x-common-config: &common-config
  build: .
  env_file: .env
  volumes:
    - ./datalake:/app/datalake
    - ./sqlMesh:/app/sqlMesh
  environment:
    # Azure Blob Storage Configuration
    - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
    - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
    - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
    - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    - ENABLE_AZURE_UPLOAD=${ENABLE_AZURE_UPLOAD}
    # Environment Configuration
    - TARGET=${TARGET}
    - USERNAME=${USERNAME}
    - DB_PATH=/app/sqlMesh/unosaa_data_pipeline.db

services:
  pipeline:
    <<: *common-config
    container_name: osaa-mvp-main
    environment:
      - GATEWAY=${GATEWAY:-local}
    profiles:
      - default

  ui:
    <<: *common-config
    container_name: osaa-mvp-ui
    working_dir: /app/sqlMesh
    command: ["ui"]
    environment:
      - GATEWAY=local
    ports:
      - "${UI_PORT:-8080}:${UI_PORT:-8080}"
    profiles:
      - ui
