gateways:
  local:
    connection:
      type: duckdb
      database: unosaa_data_pipeline.db
      # Configure DuckDB with httpfs extension for S3 access
      extensions: ['httpfs']

  shared_state:
    connection:
      type: duckdb
      database: unosaa_data_pipeline.db
      extensions: ['httpfs']

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2024-11-01
