gateways:
  local:
    connection:
      type: duckdb
      database: osaa_mvp.db
      # Configure DuckDB with httpfs extension for S3 access
      extensions: ['httpfs']

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2024-11-01
