gateways:
  local:
    connection:
      type: duckdb
      database: osaa_mvp.db
      # Configure DuckDB with httpfs extension for S3 access
      extensions: ['httpfs']

  shared_state:
    connection:
      type: duckdb
      database: osaa_mvp.db
      extensions: ['httpfs']
    state_connection:
      type: postgres
      host: {{ env_var ('POSTGRES_HOST') }}
      port: {{ env_var ('POSTGRES_PORT') | int }}
      user: {{ env_var ('POSTGRES_USER') }}
      password: {{ env_var ('POSTGRES_PASSWORD') }}
      database: {{ env_var ('POSTGRES_DATABASE') }}
      pre_ping: True

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2024-11-01
