name: Daily Transformation Job

on:
  schedule:
    # Run at 9:00 AM EST every day
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Transform Command
        env:
          TARGET: Prod
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
        run: |
          docker run --rm \
            -e TARGET=$TARGET \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
            ghcr.io/${{ github.repository }}:latest \
            transform
