name: Daily Transformation Job

on:
  schedule:
    # Run at 9:00 AM EST every day
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Transform Command
        env:
          TARGET: Prod
          GATEWAY: shared_state
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME || 'osaa-mvp' }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE || 'postgres' }}
          USERNAME: github-ci-daily
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT || '5432' }}
        run: |
          docker run --rm \
            -e TARGET=$TARGET \
            -e GATEWAY=$GATEWAY \
            -e AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
            -e S3_BUCKET_NAME=$S3_BUCKET_NAME \
            -e USERNAME=$USERNAME \
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            -e POSTGRES_PORT=$POSTGRES_PORT \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DATABASE=$POSTGRES_DATABASE \
            ghcr.io/${{ github.repository }}:latest \
            transform
