name: Build, Test, and Deploy Container on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-test-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Container
      run: docker build -t osaa-mvp .

    - name: Run Container with Dry Run
      id: run-container
      run: |
        docker run --name osaa-mvp-test -e TARGET=int osaa-mvp transform_dry_run
      continue-on-error: true

    - name: Check Container Logs
      run: docker logs osaa-mvp-test

    - name: Check Container Status
      run: |
        container_status=$(docker inspect --format='{{.State.Status}}' osaa-mvp-test)
        if [ "$container_status" != "exited" ] || [ "$(docker inspect --format='{{.State.ExitCode}}' osaa-mvp-test)" != "0" ]; then
          echo "Container failed to run correctly"
          exit 1
        fi

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest
          type=ref,event=branch
          type=sha,format=long

    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Cleanup
      if: always()
      run: |
        docker stop osaa-mvp-test || true
        docker rm osaa-mvp-test || true
