name: Build and Test Container on Push

on: push

jobs:
  build-and-test-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Container
      run: docker build -t osaa-mvp .

    - name: Run Container with Dry Run
      id: run-container
      env:
        TARGET: ${{ secrets.TARGET || 'dev' }}
        GATEWAY: ${{ secrets.GATEWAY || 'shared_state' }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
      run: |
        docker run --name osaa-mvp-test \
          -e TARGET=$TARGET \
          -e GATEWAY=$GATEWAY \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
          -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
          -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          -e POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} \
          osaa-mvp transform_dry_run
      continue-on-error: true

    - name: Check Container Logs
      run: docker logs osaa-mvp-test

    - name: Check Container Status
      run: |
        container_status=$(docker inspect --format='{{.State.Status}}' osaa-mvp-test)
        if [ "$container_status" != "exited" ] || [ "$(docker inspect --format='{{.State.ExitCode}}' osaa-mvp-test)" != "0" ]; then
          echo "Container failed to run correctly"
          exit 1
        fi

    - name: Cleanup
      if: always()
      run: |
        docker stop osaa-mvp-test || true
        docker rm osaa-mvp-test || true
