name: Build and Test Container on Push

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test-container:
    runs-on: ubuntu-latest
      env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      TARGET: prod
      USERNAME: ${{ secrets.USERNAME }}
      GATEWAY: ${{ secrets.GATEWAY }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Container
      run: docker build -t osaa-mvp .

    - name: Run Container with Dry Run
      id: run-container
      run: |
        docker run --name osaa-mvp-test -e TARGET=int osaa-mvp transform_dry_run
      continue-on-error: true

    - name: Check Container Logs
      run: docker logs osaa-mvp-test

    - name: Check Container Status
      run: |
        container_status=$(docker inspect --format='{{.State.Status}}' osaa-mvp-test)
        if [ "$container_status" != "exited" ] || [ "$(docker inspect --format='{{.State.ExitCode}}' osaa-mvp-test)" != "0" ]; then
          echo "Container failed to run correctly"
          exit 1
        fi

    - name: Cleanup
      if: always()
      run: |
        docker stop osaa-mvp-test || true
        docker rm osaa-mvp-test || true
